### ISSUE TITLE
Config, and a conflict with shoulder surfing

### ISSUE THREAD

**Issue by slovinsqui** [Krash220/CrosshairBobbingMod#1]
being able to customize the animations from this mod would be nice, plus when usen with shoulder surfing mod, the UI (most obvious case being inventories) looks messed up when playing in 3rd person

**Comment by InformationKiller** [comment]
I will consider it in the future.
The animation of this Mod mainly relies on the animation data provided by the vanilla game, so there is no consideration for shoulder surfacing.
