### ISSUE TITLE
能否做到使蓄力条不跟随准星移动

### ISSUE THREAD

**Issue by xianhongtao** [Krash220/CrosshairBobbingMod#6]
在PVP时准星的晃动会在一定程度上导致看不清蓄力条

**Comment by InformationKiller** [comment]
这俩是一起渲染的，很难给他们分开，如果硬要分开的话可能会导致严重的兼容问题（把别的mod弄炸啦什么的）所以我并不打算做。

**Comment by xianhongtao** [comment]
好吧，有点可惜，但还是谢谢大大的mod拉
